# permissions for end users to edit orderservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: orderservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: restaurant-mgmt-operator
    app.kubernetes.io/part-of: restaurant-mgmt-operator
    app.kubernetes.io/managed-by: kustomize
  name: orderservice-editor-role
rules:
- apiGroups:
  - backend.xyzcompany.com
  resources:
  - orderservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backend.xyzcompany.com
  resources:
  - orderservices/status
  verbs:
  - get
